"""Added light and thermostat tables

Revision ID: 17f3b7e50a62
Revises: 0d4e955ae85d
Create Date: 2022-11-15 14:51:07.035196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f3b7e50a62'
down_revision = '0d4e955ae85d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
