"""Added light and thermostat tables

Revision ID: 17f3b7e50a62
Revises: 0d4e955ae85d
Create Date: 2022-11-15 14:51:07.035196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f3b7e50a62'
down_revision = '0d4e955ae85d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lights_id'), 'lights', ['id'], unique=False)
    op.create_table('thermostats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('inside_temperature', sa.Float(), nullable=True),
    sa.Column('outside_temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thermostats_id'), 'thermostats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thermostats_id'), table_name='thermostats')
    op.drop_table('thermostats')
    op.drop_index(op.f('ix_lights_id'), table_name='lights')
    op.drop_table('lights')
    # ### end Alembic commands ###
